solver/urls.py
from django.urls import path

from . import views

app_name = "solver"
urlpatterns = [
    # ex: /solver/
    path("", views.index, name="index"),
]

sudoku/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("solver/", include("solver.urls")),
]

solver/models.py
from django.db import models

# Create your models here.

solver/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .puzzle import Puzzle

# Views
def index(request):
    template = loader.get_template("solver/index.html")
    if request.method == "POST":
        # parse input
        pzl = []
        for r in range(9):
            row = []
            for c in range(9):
                val = request.POST[f"{r}-{c}"]
                if val == "":
                    row.append("?")
                else:
                    row.append(int(val))
            pzl.append(row)
        pzl = Puzzle(pzl)
        
        # solve puzzle
        if pzl.isFailed():
            context = {
                    "puzzle": pzl.state,
                    "status": "invalid"
                }
        else:
            pzl.removeSingles()
            solution = pzl.solve()
            if solution is None:
                context = {
                    "puzzle": pzl.state,
                    "status": "unsolvable"
                }
            else:
                pzl = solution
                # output solved puzzle
                context = {
                    "puzzle": pzl.state,
                    "status": "solved"
                }
    else:
        pzl = []
        for r in range(9):
            row = []
            for c in range(9):
                row.append("?")
            pzl.append(row)
        pzl = Puzzle(pzl)
        context = {
            "puzzle": pzl.state,
            "status": "input"}
    
    return HttpResponse(template.render(context, request))


    

solver/templates/solver/index.html
{% load solver_extras %} {% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Sudoku Solver</title>
    <link rel="stylesheet" href="{% static 'solver/css/output.css' %}" />
  </head>
  <body class="text-center">
    <h1 class="font-sans text-5xl text-center m-10">Sudoku Solver</h1>

    <!-- Status -->
    {% if status == "input" %}
    <p class="text-center text-md my-5">
      Input your sudoku so far. Make sure to only input numbers from 1-9.
    </p>
    {% elif status == "solved" %}
    <p class="text-center text-md my-5">Here's the solved puzzle!</p>
    {% elif status == "unsolvable" %}
    <p class="text-center text-md my-5 text-red-500">
      This puzzle has no solution.
    </p>
    {% elif status == "invalid" %}
    <p class="text-center text-md my-5 text-red-500">
      This is an invalid sudoku. Ensure you have entered only numbers from 1-9,
      with a maximum of one of each number in each row, column, and 3x3 grid.
    </p>
    {% endif %}
    <a href="{% url 'solver:index' %}" class="link">Clear Board</a>

    <!-- Board -->
    <form
      class="flex flex-col"
      action="{% url 'solver:index' %}"
      method="post"
      onsubmit="document.getElementById('loading-modal').classList.remove('hidden');"
    >
      {% csrf_token %}
      <table class="m-auto border border-2 border-black">
        {% for row in "012345678" %}
        <tr>
          {% for col in "012345678" %}
          <td
            class="{% if col|divisibleby:3 %} border-s border-black {% endif %} {% if row|divisibleby:3 %} border-t border-black {% endif %} p-0 m-0"
          >
            {% getCell puzzle row col as cell %}
            <input
              name="{{ row }}-{{ col }}"
              type="text"
              inputmode="numeric"
              pattern="[1-9]{1}"
              maxlength="1"
              class="w-12 h-12 border border-slate-200 text-center text-2xl"
              value="{% if cell|isList %}{% else %}{{ cell }}{% endif %}"
            />
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
      </table>

      <input
        type="submit"
        value="Solve"
        class="btn btn-outline btn-lg m-auto my-5"
      />
      <!-- Loading Modal -->
      <div
        class="absolute z-10 w-full h-full bg-base-100 opacity-80 top-0 left-0 hidden"
        id="loading-modal"
      >
        <div class="card w-1/3 left-1/2 top-1/3 -translate-1/2 absolute z-11">
          <div class="card-body text-center text-black">
            <h1 class="text-xl">This is going to take a minute!</h1>
            <span class="loading loading-spinner loading-xl m-auto"></span>
            <p class="text-md">
              We're using a backtracking algorithm to find a solution. This can
              take several minutes depending on the complexity of the puzzle.
              Sit back and relax while we work on it!
            </p>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>